# Generated by Django 3.2.6 on 2021-08-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Education', 'verbose_name_plural': 'Education'},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={'verbose_name': 'Work Experience', 'verbose_name_plural': 'Work Experience'},
        ),
        migrations.AddField(
            model_name='education',
            name='school',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
