# Generated by Django 3.2.6 on 2021-08-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesto', '0002_auto_20210813_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='org',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
